import * as React from "react";
import { View } from "react-native";
import { Image } from "expo-image";

interface AvatarBrutalistProps {
    id: string;
    title?: boolean;
    square?: boolean;
    size?: number;
    monochrome?: boolean;
}

const abstractImages = [
    require('@/assets/images/brutalist/abstract-1.png'),
    require('@/assets/images/brutalist/abstract-2.png'),
    require('@/assets/images/brutalist/abstract-3.png'),
    require('@/assets/images/brutalist/abstract-4.png'),
    require('@/assets/images/brutalist/abstract-5.png'),
    require('@/assets/images/brutalist/abstract-6.png'),
    require('@/assets/images/brutalist/abstract-7.png'),
    require('@/assets/images/brutalist/abstract-8.png'),
    require('@/assets/images/brutalist/abstract-9.png'),
    require('@/assets/images/brutalist/abstract-10.png'),
    require('@/assets/images/brutalist/abstract-11.png'),
    require('@/assets/images/brutalist/abstract-12.png'),
    require('@/assets/images/brutalist/abstract-13.png'),
    require('@/assets/images/brutalist/abstract-14.png'),
    require('@/assets/images/brutalist/abstract-15.png'),
    require('@/assets/images/brutalist/abstract-16.png'),
    require('@/assets/images/brutalist/abstract-17.png'),
    require('@/assets/images/brutalist/abstract-18.png'),
    require('@/assets/images/brutalist/abstract-19.png'),
    require('@/assets/images/brutalist/abstract-20.png'),
    require('@/assets/images/brutalist/abstract-21.png'),
    require('@/assets/images/brutalist/abstract-22.png'),
    require('@/assets/images/brutalist/abstract-23.png'),
    require('@/assets/images/brutalist/abstract-24.png'),
    require('@/assets/images/brutalist/abstract-25.png'),
    require('@/assets/images/brutalist/abstract-26.png'),
    require('@/assets/images/brutalist/abstract-27.png'),
    require('@/assets/images/brutalist/abstract-28.png'),
    require('@/assets/images/brutalist/abstract-29.png'),
    require('@/assets/images/brutalist/abstract-30.png'),
    require('@/assets/images/brutalist/abstract-31.png'),
    require('@/assets/images/brutalist/abstract-32.png'),
    require('@/assets/images/brutalist/abstract-33.png'),
    require('@/assets/images/brutalist/abstract-34.png'),
    require('@/assets/images/brutalist/abstract-35.png'),
    require('@/assets/images/brutalist/abstract-36.png'),
    require('@/assets/images/brutalist/abstract-37.png'),
    require('@/assets/images/brutalist/abstract-38.png'),
    require('@/assets/images/brutalist/abstract-39.png'),
    require('@/assets/images/brutalist/abstract-40.png'),
    require('@/assets/images/brutalist/abstract-41.png'),
    require('@/assets/images/brutalist/abstract-42.png'),
    require('@/assets/images/brutalist/abstract-43.png'),
    require('@/assets/images/brutalist/abstract-44.png'),
    require('@/assets/images/brutalist/abstract-45.png'),
    require('@/assets/images/brutalist/abstract-46.png'),
    require('@/assets/images/brutalist/abstract-47.png'),
    require('@/assets/images/brutalist/abstract-48.png'),
    require('@/assets/images/brutalist/abstract-49.png'),
    require('@/assets/images/brutalist/abstract-50.png'),
    require('@/assets/images/brutalist/abstract-51.png'),
    require('@/assets/images/brutalist/abstract-52.png'),
    require('@/assets/images/brutalist/abstract-53.png'),
    require('@/assets/images/brutalist/abstract-54.png'),
    require('@/assets/images/brutalist/abstract-55.png'),
    require('@/assets/images/brutalist/abstract-56.png'),
    require('@/assets/images/brutalist/abstract-57.png'),
    require('@/assets/images/brutalist/abstract-58.png'),
    require('@/assets/images/brutalist/abstract-59.png'),
    require('@/assets/images/brutalist/abstract-60.png'),
    require('@/assets/images/brutalist/abstract-61.png'),
    require('@/assets/images/brutalist/abstract-62.png'),
    require('@/assets/images/brutalist/abstract-63.png'),
    require('@/assets/images/brutalist/abstract-64.png'),
    require('@/assets/images/brutalist/abstract-65.png'),
    require('@/assets/images/brutalist/abstract-66.png'),
    require('@/assets/images/brutalist/abstract-67.png'),
    require('@/assets/images/brutalist/abstract-68.png'),
    require('@/assets/images/brutalist/abstract-69.png'),
    require('@/assets/images/brutalist/abstract-70.png'),
    require('@/assets/images/brutalist/abstract-71.png'),
    require('@/assets/images/brutalist/abstract-72.png'),
    require('@/assets/images/brutalist/abstract-73.png'),
    require('@/assets/images/brutalist/abstract-74.png'),
    require('@/assets/images/brutalist/abstract-75.png'),
    require('@/assets/images/brutalist/abstract-76.png'),
    require('@/assets/images/brutalist/abstract-77.png'),
    require('@/assets/images/brutalist/abstract-78.png'),
    require('@/assets/images/brutalist/abstract-79.png'),
    require('@/assets/images/brutalist/abstract-80.png'),
    require('@/assets/images/brutalist/abstract-81.png'),
    require('@/assets/images/brutalist/abstract-82.png'),
    require('@/assets/images/brutalist/abstract-83.png'),
    require('@/assets/images/brutalist/abstract-84.png'),
    require('@/assets/images/brutalist/abstract-85.png'),
    require('@/assets/images/brutalist/abstract-86.png'),
    require('@/assets/images/brutalist/abstract-87.png'),
    require('@/assets/images/brutalist/abstract-88.png'),
    require('@/assets/images/brutalist/abstract-89.png'),
    require('@/assets/images/brutalist/abstract-90.png'),
    require('@/assets/images/brutalist/abstract-91.png'),
    require('@/assets/images/brutalist/abstract-92.png'),
    require('@/assets/images/brutalist/abstract-93.png'),
    require('@/assets/images/brutalist/abstract-94.png'),
    require('@/assets/images/brutalist/abstract-95.png'),
    require('@/assets/images/brutalist/abstract-96.png'),
    require('@/assets/images/brutalist/abstract-97.png'),
    require('@/assets/images/brutalist/abstract-98.png'),
    require('@/assets/images/brutalist/abstract-99.png'),
    require('@/assets/images/brutalist/abstract-100.png'),
    require('@/assets/images/brutalist/abstract-101.png'),
    require('@/assets/images/brutalist/abstract-102.png'),
    require('@/assets/images/brutalist/abstract-103.png'),
    require('@/assets/images/brutalist/abstract-104.png'),
    require('@/assets/images/brutalist/abstract-105.png'),
    require('@/assets/images/brutalist/abstract-106.png'),
    require('@/assets/images/brutalist/abstract-107.png'),
    require('@/assets/images/brutalist/abstract-108.png'),
    require('@/assets/images/brutalist/abstract-109.png'),
    require('@/assets/images/brutalist/abstract-110.png'),
    require('@/assets/images/brutalist/abstract-111.png'),
    require('@/assets/images/brutalist/abstract-112.png'),
    require('@/assets/images/brutalist/abstract-113.png'),
    require('@/assets/images/brutalist/abstract-114.png'),
    require('@/assets/images/brutalist/abstract-115.png'),
    require('@/assets/images/brutalist/abstract-116.png'),
    require('@/assets/images/brutalist/abstract-117.png'),
    require('@/assets/images/brutalist/abstract-118.png'),
    require('@/assets/images/brutalist/abstract-119.png'),
    require('@/assets/images/brutalist/abstract-120.png'),
    require('@/assets/images/brutalist/abstract-121.png'),
    require('@/assets/images/brutalist/abstract-122.png'),
    require('@/assets/images/brutalist/abstract-123.png'),
    require('@/assets/images/brutalist/abstract-124.png'),
    require('@/assets/images/brutalist/abstract-125.png'),
    require('@/assets/images/brutalist/abstract-126.png'),
    require('@/assets/images/brutalist/abstract-127.png'),
    require('@/assets/images/brutalist/abstract-128.png'),
    require('@/assets/images/brutalist/abstract-129.png'),
    require('@/assets/images/brutalist/abstract-130.png'),
    require('@/assets/images/brutalist/abstract-131.png'),
    require('@/assets/images/brutalist/abstract-132.png'),
    require('@/assets/images/brutalist/abstract-133.png'),
    require('@/assets/images/brutalist/abstract-134.png'),
    require('@/assets/images/brutalist/abstract-135.png'),
    require('@/assets/images/brutalist/abstract-136.png'),
    require('@/assets/images/brutalist/abstract-137.png'),
    require('@/assets/images/brutalist/abstract-138.png'),
    require('@/assets/images/brutalist/abstract-139.png'),
    require('@/assets/images/brutalist/abstract-140.png'),
    require('@/assets/images/brutalist/abstract-141.png'),
    require('@/assets/images/brutalist/abstract-142.png'),
    require('@/assets/images/brutalist/abstract-143.png'),
    require('@/assets/images/brutalist/abstract-144.png'),
    require('@/assets/images/brutalist/abstract-145.png'),
    require('@/assets/images/brutalist/abstract-146.png'),
    require('@/assets/images/brutalist/abstract-147.png'),
    require('@/assets/images/brutalist/abstract-148.png'),
    require('@/assets/images/brutalist/abstract-149.png'),
    require('@/assets/images/brutalist/abstract-150.png'),
    require('@/assets/images/brutalist/abstract-151.png'),
    require('@/assets/images/brutalist/abstract-152.png'),
    require('@/assets/images/brutalist/abstract-153.png'),
    require('@/assets/images/brutalist/abstract-154.png'),
    require('@/assets/images/brutalist/abstract-155.png'),
    require('@/assets/images/brutalist/abstract-156.png'),
    require('@/assets/images/brutalist/abstract-157.png'),
    require('@/assets/images/brutalist/abstract-158.png'),
    require('@/assets/images/brutalist/abstract-159.png'),
    require('@/assets/images/brutalist/abstract-160.png'),
    require('@/assets/images/brutalist/abstract-161.png'),
    require('@/assets/images/brutalist/abstract-162.png'),
    require('@/assets/images/brutalist/abstract-163.png'),
    require('@/assets/images/brutalist/abstract-164.png'),
    require('@/assets/images/brutalist/abstract-165.png'),
    require('@/assets/images/brutalist/abstract-166.png'),
    require('@/assets/images/brutalist/abstract-167.png'),
    require('@/assets/images/brutalist/abstract-168.png'),
    require('@/assets/images/brutalist/abstract-169.png'),
    require('@/assets/images/brutalist/abstract-170.png'),
    require('@/assets/images/brutalist/abstract-171.png'),
    require('@/assets/images/brutalist/abstract-172.png'),
    require('@/assets/images/brutalist/abstract-173.png'),
    require('@/assets/images/brutalist/abstract-174.png'),
    require('@/assets/images/brutalist/abstract-175.png'),
    require('@/assets/images/brutalist/abstract-176.png'),
    require('@/assets/images/brutalist/abstract-177.png'),
    require('@/assets/images/brutalist/abstract-178.png'),
    require('@/assets/images/brutalist/abstract-179.png'),
    require('@/assets/images/brutalist/abstract-180.png'),
    require('@/assets/images/brutalist/abstract-181.png'),
    require('@/assets/images/brutalist/abstract-182.png'),
    require('@/assets/images/brutalist/abstract-183.png'),
    require('@/assets/images/brutalist/abstract-184.png'),
    require('@/assets/images/brutalist/abstract-185.png'),
    require('@/assets/images/brutalist/abstract-186.png'),
    require('@/assets/images/brutalist/abstract-187.png'),
    require('@/assets/images/brutalist/abstract-188.png'),
    require('@/assets/images/brutalist/abstract-189.png'),
    require('@/assets/images/brutalist/abstract-190.png'),
    require('@/assets/images/brutalist/abstract-191.png'),
    require('@/assets/images/brutalist/abstract-192.png'),
    require('@/assets/images/brutalist/abstract-193.png'),
    require('@/assets/images/brutalist/abstract-194.png'),
    require('@/assets/images/brutalist/abstract-195.png'),
    require('@/assets/images/brutalist/abstract-196.png'),
    require('@/assets/images/brutalist/abstract-197.png'),
    require('@/assets/images/brutalist/abstract-198.png'),
    require('@/assets/images/brutalist/abstract-199.png'),
    require('@/assets/images/brutalist/abstract-200.png'),
    require('@/assets/images/brutalist/abstract-201.png'),
    require('@/assets/images/brutalist/abstract-202.png'),
    require('@/assets/images/brutalist/abstract-203.png'),
    require('@/assets/images/brutalist/abstract-204.png'),
    require('@/assets/images/brutalist/abstract-205.png'),
    require('@/assets/images/brutalist/abstract-206.png'),
    require('@/assets/images/brutalist/abstract-207.png'),
    require('@/assets/images/brutalist/abstract-208.png'),
    require('@/assets/images/brutalist/abstract-209.png'),
    require('@/assets/images/brutalist/abstract-210.png'),
    require('@/assets/images/brutalist/abstract-211.png'),
    require('@/assets/images/brutalist/abstract-212.png'),
    require('@/assets/images/brutalist/abstract-213.png'),
    require('@/assets/images/brutalist/abstract-214.png'),
    require('@/assets/images/brutalist/abstract-215.png'),
    require('@/assets/images/brutalist/abstract-216.png'),
    require('@/assets/images/brutalist/abstract-217.png'),
    require('@/assets/images/brutalist/abstract-218.png'),
    require('@/assets/images/brutalist/abstract-219.png'),
    require('@/assets/images/brutalist/abstract-220.png'),
    require('@/assets/images/brutalist/abstract-221.png'),
    require('@/assets/images/brutalist/abstract-222.png'),
    require('@/assets/images/brutalist/abstract-223.png'),
    require('@/assets/images/brutalist/abstract-224.png'),
    require('@/assets/images/brutalist/abstract-225.png'),
    require('@/assets/images/brutalist/abstract-226.png'),
    require('@/assets/images/brutalist/abstract-227.png'),
    require('@/assets/images/brutalist/abstract-228.png'),
    require('@/assets/images/brutalist/abstract-229.png'),
    require('@/assets/images/brutalist/abstract-230.png'),
    require('@/assets/images/brutalist/abstract-231.png'),
    require('@/assets/images/brutalist/abstract-232.png'),
    require('@/assets/images/brutalist/abstract-233.png'),
    require('@/assets/images/brutalist/abstract-234.png'),
    require('@/assets/images/brutalist/abstract-235.png'),
    require('@/assets/images/brutalist/abstract-236.png'),
    require('@/assets/images/brutalist/abstract-237.png'),
    require('@/assets/images/brutalist/abstract-238.png'),
    require('@/assets/images/brutalist/abstract-239.png'),
    require('@/assets/images/brutalist/abstract-240.png'),
    require('@/assets/images/brutalist/abstract-241.png'),
    require('@/assets/images/brutalist/abstract-242.png'),
    require('@/assets/images/brutalist/abstract-243.png'),
    require('@/assets/images/brutalist/abstract-244.png'),
    require('@/assets/images/brutalist/abstract-245.png'),
    require('@/assets/images/brutalist/abstract-246.png'),
    require('@/assets/images/brutalist/abstract-247.png'),
    require('@/assets/images/brutalist/abstract-248.png'),
    require('@/assets/images/brutalist/abstract-249.png'),
    require('@/assets/images/brutalist/abstract-250.png'),
    require('@/assets/images/brutalist/abstract-251.png'),
    require('@/assets/images/brutalist/abstract-252.png'),
    require('@/assets/images/brutalist/abstract-253.png'),
    require('@/assets/images/brutalist/abstract-254.png'),
    require('@/assets/images/brutalist/abstract-255.png'),
    require('@/assets/images/brutalist/abstract-256.png'),
    require('@/assets/images/brutalist/abstract-257.png'),
    require('@/assets/images/brutalist/abstract-258.png'),
    require('@/assets/images/brutalist/abstract-259.png'),
    require('@/assets/images/brutalist/abstract-260.png'),
    require('@/assets/images/brutalist/abstract-261.png'),
    require('@/assets/images/brutalist/abstract-262.png'),
];

const bauhausImages = [
    require('@/assets/images/brutalist/bauhaus-1.png'),
    require('@/assets/images/brutalist/bauhaus-2.png'),
    require('@/assets/images/brutalist/bauhaus-3.png'),
    require('@/assets/images/brutalist/bauhaus-4.png'),
    require('@/assets/images/brutalist/bauhaus-5.png'),
    require('@/assets/images/brutalist/bauhaus-6.png'),
    require('@/assets/images/brutalist/bauhaus-7.png'),
    require('@/assets/images/brutalist/bauhaus-8.png'),
    require('@/assets/images/brutalist/bauhaus-9.png'),
    require('@/assets/images/brutalist/bauhaus-10.png'),
    require('@/assets/images/brutalist/bauhaus-11.png'),
    require('@/assets/images/brutalist/bauhaus-12.png'),
    require('@/assets/images/brutalist/bauhaus-13.png'),
    require('@/assets/images/brutalist/bauhaus-14.png'),
    require('@/assets/images/brutalist/bauhaus-15.png'),
    require('@/assets/images/brutalist/bauhaus-16.png'),
    require('@/assets/images/brutalist/bauhaus-17.png'),
    require('@/assets/images/brutalist/bauhaus-18.png'),
    require('@/assets/images/brutalist/bauhaus-19.png'),
    require('@/assets/images/brutalist/bauhaus-20.png'),
    require('@/assets/images/brutalist/bauhaus-21.png'),
    require('@/assets/images/brutalist/bauhaus-22.png'),
    require('@/assets/images/brutalist/bauhaus-23.png'),
    require('@/assets/images/brutalist/bauhaus-24.png'),
    require('@/assets/images/brutalist/bauhaus-25.png'),
    require('@/assets/images/brutalist/bauhaus-26.png'),
    require('@/assets/images/brutalist/bauhaus-27.png'),
    require('@/assets/images/brutalist/bauhaus-28.png'),
    require('@/assets/images/brutalist/bauhaus-29.png'),
    require('@/assets/images/brutalist/bauhaus-30.png'),
    require('@/assets/images/brutalist/bauhaus-31.png'),
    require('@/assets/images/brutalist/bauhaus-32.png'),
    require('@/assets/images/brutalist/bauhaus-33.png'),
    require('@/assets/images/brutalist/bauhaus-34.png'),
    require('@/assets/images/brutalist/bauhaus-35.png'),
    require('@/assets/images/brutalist/bauhaus-36.png'),
    require('@/assets/images/brutalist/bauhaus-37.png'),
    require('@/assets/images/brutalist/bauhaus-38.png'),
    require('@/assets/images/brutalist/bauhaus-39.png'),
    require('@/assets/images/brutalist/bauhaus-40.png'),
];

const brutalismImages = [
    require('@/assets/images/brutalist/brutalism-1.png'),
    require('@/assets/images/brutalist/brutalism-2.png'),
    require('@/assets/images/brutalist/brutalism-3.png'),
    require('@/assets/images/brutalist/brutalism-4.png'),
    require('@/assets/images/brutalist/brutalism-5.png'),
    require('@/assets/images/brutalist/brutalism-6.png'),
    require('@/assets/images/brutalist/brutalism-7.png'),
    require('@/assets/images/brutalist/brutalism-8.png'),
    require('@/assets/images/brutalist/brutalism-9.png'),
    require('@/assets/images/brutalist/brutalism-10.png'),
    require('@/assets/images/brutalist/brutalism-11.png'),
    require('@/assets/images/brutalist/brutalism-12.png'),
    require('@/assets/images/brutalist/brutalism-13.png'),
    require('@/assets/images/brutalist/brutalism-14.png'),
    require('@/assets/images/brutalist/brutalism-15.png'),
    require('@/assets/images/brutalist/brutalism-16.png'),
    require('@/assets/images/brutalist/brutalism-17.png'),
    require('@/assets/images/brutalist/brutalism-18.png'),
    require('@/assets/images/brutalist/brutalism-19.png'),
    require('@/assets/images/brutalist/brutalism-20.png'),
    require('@/assets/images/brutalist/brutalism-21.png'),
    require('@/assets/images/brutalist/brutalism-22.png'),
    require('@/assets/images/brutalist/brutalism-23.png'),
    require('@/assets/images/brutalist/brutalism-24.png'),
    require('@/assets/images/brutalist/brutalism-25.png'),
    require('@/assets/images/brutalist/brutalism-26.png'),
    require('@/assets/images/brutalist/brutalism-27.png'),
    require('@/assets/images/brutalist/brutalism-28.png'),
    require('@/assets/images/brutalist/brutalism-29.png'),
    require('@/assets/images/brutalist/brutalism-30.png'),
    require('@/assets/images/brutalist/brutalism-31.png'),
    require('@/assets/images/brutalist/brutalism-32.png'),
    require('@/assets/images/brutalist/brutalism-33.png'),
    require('@/assets/images/brutalist/brutalism-34.png'),
    require('@/assets/images/brutalist/brutalism-35.png'),
    require('@/assets/images/brutalist/brutalism-36.png'),
    require('@/assets/images/brutalist/brutalism-37.png'),
    require('@/assets/images/brutalist/brutalism-38.png'),
    require('@/assets/images/brutalist/brutalism-39.png'),
    require('@/assets/images/brutalist/brutalism-40.png'),
    require('@/assets/images/brutalist/brutalism-41.png'),
    require('@/assets/images/brutalist/brutalism-42.png'),
    require('@/assets/images/brutalist/brutalism-43.png'),
    require('@/assets/images/brutalist/brutalism-44.png'),
    require('@/assets/images/brutalist/brutalism-45.png'),
    require('@/assets/images/brutalist/brutalism-46.png'),
    require('@/assets/images/brutalist/brutalism-47.png'),
    require('@/assets/images/brutalist/brutalism-48.png'),
    require('@/assets/images/brutalist/brutalism-49.png'),
    require('@/assets/images/brutalist/brutalism-50.png'),
    require('@/assets/images/brutalist/brutalism-51.png'),
    require('@/assets/images/brutalist/brutalism-52.png'),
    require('@/assets/images/brutalist/brutalism-53.png'),
    require('@/assets/images/brutalist/brutalism-54.png'),
    require('@/assets/images/brutalist/brutalism-55.png'),
    require('@/assets/images/brutalist/brutalism-56.png'),
    require('@/assets/images/brutalist/brutalism-57.png'),
    require('@/assets/images/brutalist/brutalism-58.png'),
    require('@/assets/images/brutalist/brutalism-59.png'),
    require('@/assets/images/brutalist/brutalism-60.png'),
    require('@/assets/images/brutalist/brutalism-61.png'),
    require('@/assets/images/brutalist/brutalism-62.png'),
    require('@/assets/images/brutalist/brutalism-63.png'),
    require('@/assets/images/brutalist/brutalism-64.png'),
    require('@/assets/images/brutalist/brutalism-65.png'),
    require('@/assets/images/brutalist/brutalism-66.png'),
    require('@/assets/images/brutalist/brutalism-67.png'),
    require('@/assets/images/brutalist/brutalism-68.png'),
    require('@/assets/images/brutalist/brutalism-69.png'),
    require('@/assets/images/brutalist/brutalism-70.png'),
    require('@/assets/images/brutalist/brutalism-71.png'),
    require('@/assets/images/brutalist/brutalism-72.png'),
    require('@/assets/images/brutalist/brutalism-73.png'),
    require('@/assets/images/brutalist/brutalism-74.png'),
    require('@/assets/images/brutalist/brutalism-75.png'),
    require('@/assets/images/brutalist/brutalism-76.png'),
    require('@/assets/images/brutalist/brutalism-77.png'),
    require('@/assets/images/brutalist/brutalism-78.png'),
    require('@/assets/images/brutalist/brutalism-79.png'),
    require('@/assets/images/brutalist/brutalism-80.png'),
    require('@/assets/images/brutalist/brutalism-81.png'),
    require('@/assets/images/brutalist/brutalism-82.png'),
    require('@/assets/images/brutalist/brutalism-83.png'),
    require('@/assets/images/brutalist/brutalism-84.png'),
    require('@/assets/images/brutalist/brutalism-85.png'),
    require('@/assets/images/brutalist/brutalism-86.png'),
    require('@/assets/images/brutalist/brutalism-87.png'),
    require('@/assets/images/brutalist/brutalism-88.png'),
    require('@/assets/images/brutalist/brutalism-89.png'),
    require('@/assets/images/brutalist/brutalism-90.png'),
    require('@/assets/images/brutalist/brutalism-91.png'),
    require('@/assets/images/brutalist/brutalism-92.png'),
    require('@/assets/images/brutalist/brutalism-93.png'),
    require('@/assets/images/brutalist/brutalism-94.png'),
    require('@/assets/images/brutalist/brutalism-95.png'),
    require('@/assets/images/brutalist/brutalism-96.png'),
    require('@/assets/images/brutalist/brutalism-97.png'),
    require('@/assets/images/brutalist/brutalism-98.png'),
    require('@/assets/images/brutalist/brutalism-99.png'),
    require('@/assets/images/brutalist/brutalism-100.png'),
    require('@/assets/images/brutalist/brutalism-101.png'),
    require('@/assets/images/brutalist/brutalism-102.png'),
    require('@/assets/images/brutalist/brutalism-103.png'),
    require('@/assets/images/brutalist/brutalism-104.png'),
    require('@/assets/images/brutalist/brutalism-105.png'),
    require('@/assets/images/brutalist/brutalism-106.png'),
    require('@/assets/images/brutalist/brutalism-107.png'),
    require('@/assets/images/brutalist/brutalism-108.png'),
    require('@/assets/images/brutalist/brutalism-109.png'),
    require('@/assets/images/brutalist/brutalism-110.png'),
    require('@/assets/images/brutalist/brutalism-111.png'),
    require('@/assets/images/brutalist/brutalism-112.png'),
    require('@/assets/images/brutalist/brutalism-113.png'),
    require('@/assets/images/brutalist/brutalism-114.png'),
    require('@/assets/images/brutalist/brutalism-115.png'),
    require('@/assets/images/brutalist/brutalism-116.png'),
    require('@/assets/images/brutalist/brutalism-117.png'),
    require('@/assets/images/brutalist/brutalism-118.png'),
];

const allImages = [...abstractImages, ...bauhausImages, ...brutalismImages];

const colorPairs = [
    { tint: '#FFA617', background: '#0056B3' }, // Orange → Deep blue
    { tint: '#59C9DF', background: '#DC2626' }, // Cyan → Bold red
    { tint: '#C678FF', background: '#16A34A' }, // Purple → Forest green
    { tint: '#FF79D7', background: '#047857' }, // Pink → Teal green
    { tint: '#FFD800', background: '#4C1D95' }, // Yellow → Deep purple
    { tint: '#84E600', background: '#C026D3' }  // Lime → Magenta
];

function hashCode(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
        const char = str.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash = hash & hash;
    }
    return Math.abs(hash);
}

export const AvatarBrutalist = React.memo((props: AvatarBrutalistProps) => {
    const { id, size = 32, square = false, monochrome = false } = props;

    const imageIndex = hashCode(id) % allImages.length;
    const colorIndex = hashCode(id + 'color') % colorPairs.length;

    const imageSource = allImages[imageIndex];
    const colorPair = colorPairs[colorIndex];
    const tintColor = monochrome ? '#999999' : colorPair.tint;
    const backgroundColor = monochrome ? '#F0F0F0' : colorPair.background;

    const dimension = square ? size : size;
    const borderRadius = square ? 0 : size / 2;

    return (
        <View
            style={{
                width: dimension,
                height: dimension,
                borderRadius,
                backgroundColor,
                // borderWidth: square ? 0 : 0.5,
                // borderColor: 'rgba(0, 0, 0, 0.1)',
                justifyContent: 'center',
                alignItems: 'center'
            }}
        >
            <Image
                source={imageSource}
                style={{
                    width: dimension * 0.8,
                    height: dimension * 0.8,
                    borderRadius
                }}
                tintColor={tintColor}
            />
        </View>
    );
});